---
repo-name: peripherals-slack
categories:
- Collaboration
- Social
display-name: Slack
manufacture: Slack
product: Slack
description: When your team needs to kick off a project, hire a new employee, deploy some code, review a sales contract, finalize next year's budget, measure an A/B test, plan your next office opening, and more, Slack has you covered.
